name: Maven Build & Docker Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    name: Build JAR & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'

      - name: Build JAR
        run: mvn package -DskipTests

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ajitdalvi1/myapp:latest .
      
      - name: Push Docker Image
        run: |
          docker push ajitdalvi1/myapp:latest
